### ISSUE TITLE
Update the about info of this repo

### ISSUE THREAD

**Issue by ShadowArcanist** [Mintplex-Labs/anythingllm-docs#10]
At the moment this is the about info:

![image](https://github.com/Mintplex-Labs/anythingllm-docs/assets/162910371/8843adba-eccf-44c4-a27d-eeb92f125c15)

**Comment by timothycarambat** [comment]
What is the issue with it?

**Comment by ShadowArcanist** [comment]
@timothycarambat it has to show the url for our docs website no? 
Docs website -- https://docs.useanything.com/ 🤔

**Comment by timothycarambat** [comment]
Oh, no Vercel overwrites that automatically for the repo connector (no idea why)
