### ISSUE TITLE
Anything LLM Integration for Drupal Wiki

### ISSUE THREAD

**Issue by andul** [Mintplex-Labs/anythingllm-docs#115]
Hi,

we like to create an Anything LLM data connector for [Drupal Wiki](https://drupal-wiki.com). We would like to start the implementation as soon as possible cause we have resources available now. Can we provide pull requests in order to contribute it to Anything LLM? Later on when the planned AnythingLLM Community Hub is in place the data connector could be relocated accordingly.

Thanks in advance,
André

**Comment by timothycarambat** [comment]
Closing since its not an "issue" and just keeping Github about issues - this seems more like a question for general implementation and use case. Should have data connector plugins + docs live within the next few weeks

**Comment by andul** [comment]
Hi Timothy, thanks for your quick response. Can you point out which of the data connectors should be used as reference implementation so we can orientate us on the best one?
