### ISSUE TITLE
which are “Ollama Embedder” models?

### ISSUE THREAD

**Issue by yaya159456** [Mintplex-Labs/anythingllm-docs#12]
which models are embedding models? except in ollama?

**Comment by timothycarambat** [comment]
[snowflake-arctic-embed](https://ollama.com/library/snowflake-arctic-embed)
[mxbai-embed-large](https://ollama.com/library/mxbai-embed-large)
[nomic-embed-text](https://ollama.com/library/nomic-embed-text)

are the usual ones, there may be more but you'll have to check with their project to be sure.
