### ISSUE TITLE
Feedback for “v1.5.3”

### ISSUE THREAD

**Issue by zimoai** [Mintplex-Labs/anythingllm-docs#15]
when create workspace  -->>  Error: Invalid `prisma.workspaces.create()` invocation: The column `main.workspaces.queryRefusalResponse` does not exist in the current database.
how to fix it? by the way 1.5.3 windows version

**Comment by timothycarambat** [comment]
Is this on a fresh install of the app on desktop? What version of windows are you on (Home/server/etc) and are you the admin on that windows version. That error usually indicates a permission issue and the DB cannot migrate

**Comment by zimoai** [comment]
no, 1.5.2 works fine.  
版本	Windows 11 家庭中文版 
版本	23H2
安装日期	‎2024/‎2/‎18
操作系统版本	22631.3447
it is a Chinese version
