### ISSUE TITLE
How to setup for development - Windows

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anythingllm-docs#18]
> From https://github.com/Mintplex-Labs/anything-llm/issues/1346

Description
In case anyone is developing on Windows, this is what I had to do...

yarn setup will not work all the way on windows because yarn setup:envs part fails due to the cp command not existing... but, you can still run yarn setup and then manually copy:

copy ./frontend/.env.example ./frontend/.env
copy ./server/.env.example ./server/.env.development
copy ./collector/.env.example ./collector/.env
copy ./docker/.env.example ./docker/.env
But then you have to run yarn prisma:setup manually, because that part was not reached in yarn setup call, after the failure of yarn setup:envs...

Finally, the NODE_ENV issue.

In all 3 package.json files inside server, client and collector folders I had to change NODE_ENV=development into set NODE_ENV=development &&.

Then in the frontend folder, nothing else was needed.

But, in both server/index.js and collector/index.js files, I added this line on top: process.env.NODE_ENV = process.env.NODE_ENV.trim();. This is because the set change sets the extra space, sadly. Alternatively, [setenv](https://www.npmjs.com/package/setenv) may be a solution but I figured adding a single line is less disruptive than adding a whole package...

I was then able to start all three with:
yarn dev:server
yarn dev:frontend
yarn dev:collector

Naturally, these changes must not be pushed in your merge requests...

**Comment by ShadowArcanist** [comment]
@timothycarambat can I just create a new page on docs and copy paste your message (you sent above)? or is there anything else we have to add to your message ?

**Comment by timothycarambat** [comment]
There is really nothing new. The only detail is this is for local development and you should **not** run the app this way for production instances

**Comment by yongshengma** [comment]
cp command works in my Windows VS Code, so this part is not necessary:

> yarn setup will not work all the way on windows because yarn setup:envs part fails due to the cp command not existing... but, you can still run yarn setup and then manually copy:
> 
> copy ./frontend/.env.example ./frontend/.env
> copy ./server/.env.example ./server/.env.development
> copy ./collector/.env.example ./collector/.env
> copy ./docker/.env.example ./docker/.env
> But then you have to run yarn prisma:setup manually, because that part was not reached in yarn setup call, after the failure of yarn setup:envs...

**Comment by timothycarambat** [comment]
Are you in WSL or are using some other Linux emulation shell `cp` is not a valid Powershell command

**Comment by timothycarambat** [comment]
There is no `.env.example` in the root of the directory. In WSL you can just use the Linux setup, so all you need is

- NodeJS 18.13.0
- yarn

Then
```
git clone git@github.com:Mintplex-Labs/anything-llm.git
cd anything-llm
yarn setup
yarn prisma:migrate && yarn prisma:generate
```

Now everything is set up and installed. You can edit `server/.env.development` with your settings and keys and to start the development you can run each of these commands in separate windows from the project root:
`yarn dev:server` - starts backend
`yarn dev:frontend` - starts frontend
`yarn dev:collector` - stars documents collector

I am not sure what you are doing in the above screenshots since it looks like you didn't even git clone the repo since the folder is totally empty

**Comment by yongshengma** [comment]
> I am not sure what you are doing in the above screenshots since it looks like you didn't even git clone the repo since the folder is totally empty

Thanks for summary! The above is just to show linux-like command works in my powershell. Except that the operations are totally garbage ......
