### ISSUE TITLE
[FAQ] Agents not giving proper responses

### ISSUE THREAD

**Issue by ShadowArcanist** [Mintplex-Labs/anythingllm-docs#20]
On our discord we got alot of questions like 
- Agents were not working for me
- Agents were saying "I can't use internet"

In most cases the user is:
- Not using the model works well with Agents (like they use llama 3 8b 4bit Q)
- Not giving proper prompt to the Agent
- Expecting results that agents are not capable to do

**Comment by timothycarambat** [comment]
resolved by #33
