### ISSUE TITLE
[Question] AnythingLLM Local Docker installation guide

### ISSUE THREAD

**Issue by ShadowArcanist** [Mintplex-Labs/anythingllm-docs#25]
On https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/HOW_TO_USE_DOCKER.md for Windows install guide 3rd line has ` -ItemType File`
![image](https://github.com/Mintplex-Labs/anythingllm-docs/assets/162910371/2b81c262-ed8d-431c-9dab-6742c1c9ee14)

But on https://docs.useanything.com/getting-started/installation/self-hosted/local-docker for Windows install guide 3rd line don't have ` -ItemType File`
![image](https://github.com/Mintplex-Labs/anythingllm-docs/assets/162910371/68c71191-395c-4e8a-a588-655079bce8d0)

### Which one is correct? the code on Github repo or Docs?
Note: I noticed our docs is missing `docker pull mintplexlabs/anythingllm` command and some more info so I can fix all of these on my next PR

**Comment by timothycarambat** [comment]
The one in the github repo is more correct
