### ISSUE TITLE
[Question] How to uninstall/update anythingllm

### ISSUE THREAD

**Issue by ShadowArcanist** [Mintplex-Labs/anythingllm-docs#28]
On our [docs](https://docs.useanything.com/) we only have uninstall guide for [MacOS](https://docs.useanything.com/getting-started/installation/desktop/macos#uninstalling-the-application) and I am writing an uninstall guide (a new page which only have how to uninstall anythingllm from all platform) + an update guide similar to uninstall guide. So i want to know the following:

- How to Uninstall AnythingLLM (along with the user data) on Windows, Linux, Docker 
- How to Update AnythingLLM on Docker
- [Bonus Question] -- How to run AnythinLLM on Debug mode on Windows, Linux, Docker (we only have a [debug mode guide for macOS](https://docs.useanything.com/getting-started/installation/desktop/macos#debugging--other-tips))

Quick Note: I don't have much knowledge on using Windows, Linux and Docker, so it would be great if you could explain it in a very simple way 😄

**Comment by timothycarambat** [comment]
resolved by #33
