### ISSUE TITLE
How to use the API interface

### ISSUE THREAD

**Issue by heiheiheibj** [Mintplex-Labs/anythingllm-docs#32]
Where should I fill in the API-KEY when calling the API interface?

![image](https://github.com/Mintplex-Labs/anythingllm-docs/assets/6910198/427118c9-b44f-4ac1-913f-6a9b31f0644a)

![image](https://github.com/Mintplex-Labs/anythingllm-docs/assets/6910198/8fac1bdb-ce76-4fc8-a012-9e94854571b0)

thanks...

**Comment by timothycarambat** [comment]
When in swagger docs there is an authorize button at the top of the page you can put the key in


Which use code, head is always `Authorization: Bearer KEY`
