### ISSUE TITLE
Feedback for “Windows Installation” : choose directory for installation and downloads

### ISSUE THREAD

**Issue by Anazark** [Mintplex-Labs/anythingllm-docs#39]
Please tell me why isn't possible to choose the installation folder of the program...
And even worse why isn't possible to choose the download directory for the multi-gb LLM files, my C: directory doesn't have nearly enough storage

**Comment by timothycarambat** [comment]
You are in the wrong repo https://github.com/Mintplex-Labs/anything-llm/issues/820
