### ISSUE TITLE
vectorDB connection failed

### ISSUE THREAD

**Issue by liyingchunvip** [Mintplex-Labs/anythingllm-docs#50]
when I upload my local file into my workspace ,then I save and embed , but when I chat in the workspace , I got an error:
LanceDBError: LanceError(IO): Query vector must have non-zero length, /home/build_user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.9.18/src/dataset/scanner.rs:378:27

my local docker compose env is as follows: how can I solve this problem
version: '3.3'
services:
  anythingllm:
    privileged: true
    user: "root"
    network_mode: "host"
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
      - "3001:3001"
    environment:
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="your-jwt-secret"
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://127.0.0.1:11434
      - OLLAMA_MODEL_PREF=llama3
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      - EMBEDDING_ENGINE=ollama
      - EMBEDDING_BASE_PATH=http://127.0.0.1:11434
      - EMBEDDING_MODEL_PREF=nomic-embed-text:latest
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=lancedb
      - VECTOR_DB_PATH=/app/server/storage/lancedb
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
      - AGENT_SERPER_DEV_KEY="your-serper-dev-key"
      - AGENT_SERPLY_API_KEY="your-serply-api-key"
    volumes:
      - /home/ubuntu/anythingllm:/app/server/storage
    restart: always
  ollama:
    image: ollama
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - BIND_ADDRESS=0.0.0.0
    command: serve
    restart: always

volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/anythingllm

**Comment by timothycarambat** [comment]
> LanceDBError: LanceError(IO): Query vector must have non-zero length,

This means that the embedder failed to vectorize the query and the response came back empty (0)
_or_
You changed the embedder at some point after documents or workspaces already had been embedded or used and now the next embedder dimensions do not match what was previously used.

 What are you using as your embedder and did you even change it. Second, do you get this error on a _new_ empty workspace?
