### ISSUE TITLE
Feedback for “Roadmap”;  RAG in Obsidian

### ISSUE THREAD

**Issue by grayerbeard** [Mintplex-Labs/anythingllm-docs#51]
I currently use Obsidian with the SystemSculpt AI plug in.
This is good - can connect to Ollama or LM Studio or GPT-4o etc but lacks RAG.
To connect Ollama or LMStudio one sets them running and connect via a URL.   Could Anything LLM provide something similar but using a set of the documents on my Obsidian Vault, e,g, all the files for a certain project. (One can mark files with what project they are for and find them with Dataview).
This potentially would be a usefull item for yor roadmap either using your own Obsidian Plugin or in cooperation with SystemSculpt or one of the other plugin developers.
It would be a little like your other commercial offerings but more suitable for general public possibly with levels of sophistication accessable by a free mode then paid modes.

**Comment by timothycarambat** [comment]
We are tracking that issue in the AnythingLLM repo (https://github.com/Mintplex-Labs/anything-llm/issues/1400)

_this is for documentation only_

**Comment by tejasunku** [comment]
Don't know if you are still looking for one, but I made an extension here: https://github.com/tejasunku/anything-obsidian
