### ISSUE TITLE
Feedback for “What is AnythingLLM”

### ISSUE THREAD

**Issue by lchabin** [Mintplex-Labs/anythingllm-docs#52]
How on windows .exe install, can I select the path for installation (on another disk in my case) ?
Understand that SSDs are a scarce resource. And C: full to the brim. Not enough room for it, but plenty elsewhere.
The installation did not ask me for a path.

**Comment by timothycarambat** [comment]
Please open these issues in the right repo. This repo is for the documentation, not the product!

But this feature is already suggested in this issue:
https://github.com/Mintplex-Labs/anything-llm/issues/820

Will work on this for an incoming update. We used to support it but people kept installing it in random locations and it was causing issues
