### ISSUE TITLE
Out of box built-in Ollama is not running LLMs on GPU 

### ISSUE THREAD

**Issue by PhilBlackRose** [Mintplex-Labs/anythingllm-docs#56]
My process was:

1. Downloaded and installed Ollama
2. Ran llama2 model, realised it was not running on nvidia GPU
3. installed Nvidia CUDA
4. restart
5. Ran Ollama llama2 model again, model now runs on GPU
6. Installed AnythingLLM desktop (no docker)
7. Selected same model, llama2 but using AnythingLLM internal
8. Model runs on CPU
9. Can't find the server.log to diagnose

Issues:

Default experience is LLM does not run on GPU even when present and pre-requisites are installed in advance
Cannot locate common troubleshooting files to check if there is a problem or confirm GPUs are found in the log

Bonus:

Cannot easily locate or change the bulk storage folder for models
Tried a directory symlink but this did not work.

**Comment by timothycarambat** [comment]
Resolved by v1.5.8
