### ISSUE TITLE
Feedback for “v1.5.8” and multi GPU support

### ISSUE THREAD

**Issue by PepsiBlue14** [Mintplex-Labs/anythingllm-docs#66]
Hello! I'm working on getting multiple gpus going for my instance of anythingllm. I saw the update for automatic gpu support for NVIDIA, but I'm curious if that will utilize multiple GPUs?

**Comment by timothycarambat** [comment]
Since we use Ollama internally for the built-in LLM - there should be nothing special required on your end to use the cluster/multi-gpu setup https://github.com/ollama/ollama/issues/2672
