### ISSUE TITLE
Explanation for `--cap-add` for Docker

### ISSUE THREAD

**Issue by paulgear** [Mintplex-Labs/anythingllm-docs#75]
Re: https://docs.useanything.com/installation/desktop/linux#install-using-docker
```
...
 docker run -d -p 3001:3001 \
 --cap-add SYS_ADMIN \
 ...
```
Can there be an explanation added as to why anythingllm needs the SYS_ADMIN capability, please?

**Comment by timothycarambat** [comment]
It is for Puppeteer so you can scrape websites while still using the `sandbox` container for chromium. You would think it would be easier but it isn't without running `--no-sandbox`, which is less secure and since we dont know what websites people might scrape we should always sandbox

> --cap-add=SYS_ADMIN capability is needed to enable Chrome sandbox that makes the browser more secure. Alternatively, it should be possible to start the browser binary with the --no-sandbox flag.

**Comment by paulgear** [comment]
@timothycarambat Thanks for the prompt response.  Can you confirm: this is for running a headless chromium inside the Docker container?  What is that used for?

**Comment by timothycarambat** [comment]
When you scrape any links, this enables us to scrape the content from JS-rendered pages, which is the majority of web pages nowadays. To do this we use Puppeteer, which can use Chromium and it is unsafe to run outside of a sandbox. --cap-add allows us to run with sandboxing
