### ISSUE TITLE
Can't update the Windows desktop version

### ISSUE THREAD

**Issue by collectifweb** [Mintplex-Labs/anythingllm-docs#81]
Hello there, it seems I can't update the windows AnythingLLM program. 
![image](https://github.com/user-attachments/assets/2543629e-17f3-46e5-b24a-fb9b56638d28)
Weirdly, the app isn't running at all, even in the task manager.
I wonder if that's an issue or not.

Updating from v1.5.8 to latest.
Windows 11 here
Thanks

**Comment by timothycarambat** [comment]
Sometimes that can occur in the installer. Simply close the installer and run it again - no need to download again.
