### ISSUE TITLE
Feedback for “Support”

### ISSUE THREAD

**Issue by SheyimAtamashi** [Mintplex-Labs/anythingllm-docs#84]
Hello dear friends
I am installing your wonderful solution AnythingLLM on my intel 7 laptop with 16 RAM formatted and I have installed:

New linux mint virginia,
python 3.12.4,
node 22.6.0,
I can see their versions in the terminal
I have followed the steps for installing docker engine and successfully executed the command sudo docker run hello-world.
The docker pull mintplexlabs/anythingllm has been completed
and when I send the following command package I get the last line which looks like an API KEY:

root@nelson-NL40-50ZU:/home/nelson# export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \ 
mintplexlabs/anythingllm eda648b2e33c4954625ca38fa74648c0a0b20c7a5b23cee0c2fc9c9c1b64feb5 In the firefox browser I have NO PROXY selected in Network Settings. I try to open it at http://localhost:3001 but it says Unable to connect • Firefox can't establish a connection to the server at localhost:3001.
 • The site could be temporarily unavailable or too busy. Try again in a few moments.
 • If you are unable to load any pages, check your computer’s network connection.
 • If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

What is my mistake?
![resultado](https://github.com/user-attachments/assets/617f91f8-f188-4da4-9b3b-87052a2b0bf2)
![resultado2](https://github.com/user-attachments/assets/8a350f59-c5ee-446e-83af-ecb2ca487178)
![resultado3](https://github.com/user-attachments/assets/1a1c7b99-2d19-401f-aaa4-4102dc656e43)

Note: On another laptop on another occasion I have successfully installed anythingllm on the desktop with Linux Mint 22

**Comment by timothycarambat** [comment]
This is the repo for the documentation, not the app.

You can also view the docker logs to get more specific information on what error might be preventing the application from loading.
