### ISSUE TITLE
 Anythingllm does not start in the browser on localhost:3001

### ISSUE THREAD

**Issue by SheyimAtamashi** [Mintplex-Labs/anythingllm-docs#85]
Hello dear friends
I am installing your wonderful solution AnythingLLM on my intel 7 laptop with 16 RAM formatted and I have installed:

New linux mint virginia,
python 3.12.4,
node 22.6.0,
I can see their versions in the terminal
I have followed the steps for installing docker engine and successfully executed the command sudo docker run hello-world.
The docker pull mintplexlabs/anythingllm has been completed
and when I send the following command package I get the last line which looks like an API KEY:

root@nelson-NL40-50ZU:/home/nelson# export STORAGE_LOCATION=$HOME/anythingllm &&
mkdir -p $STORAGE_LOCATION &&
touch "$STORAGE_LOCATION/.env" &&
docker run -d -p 3001:3001
--cap-add SYS_ADMIN
-v ${STORAGE_LOCATION}:/app/server/storage
-v ${STORAGE_LOCATION}/.env:/app/server/.env
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm eda648b2e33c4954625ca38fa74648c0a0b20c7a5b23cee0c2fc9c9c1b64feb5 In the firefox browser I have NO PROXY selected in Network Settings. I try to open it at http://localhost:3001/ but it says Unable to connect • Firefox can't establish a connection to the server at localhost:3001.
• The site could be temporarily unavailable or too busy. Try again in a few moments.
• If you are unable to load any pages, check your computer’s network connection.
• If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

There should not be any problems with the wifi provider because with other applications everything works fine
What is my mistake? Please, help me.

**Comment by SheyimAtamashi** [comment]
![resultado1](https://github.com/user-attachments/assets/306554af-d443-4942-8487-282f45b78a13)
![resultado2](https://github.com/user-attachments/assets/3bf195eb-7aec-4e17-832a-1199824a2f82)
![resultado3](https://github.com/user-attachments/assets/b4b92b8b-6b56-4711-ad28-546e8ca9f67b)

**Comment by timothycarambat** [comment]
Are you able to pull the logs for the container? An Intel 7 is pretty old, but there is no telling what instruction set it has without the exact model of the CPU. 

Possibly relevant: https://github.com/Mintplex-Labs/anything-llm/issues/1331

**Also this is the documentation repo - I have said this already the last time you post this issue.**

The main anythingllm repo is https://github.com/Mintplex-Labs/anything-llm
