### ISSUE TITLE
Do anything llm has capability to use IAM role to connect to aws bedrock

### ISSUE THREAD

**Issue by NihalKA** [Mintplex-Labs/anythingllm-docs#87]
In anything llm ui is asking for aws accesskey id and secret key as a mandatory field, can I pass it as container or system variables(ACCESS_KEY and SECRET_KEY) to get connected instead of manually entering it via UI. Or can it assume a role so we can avoid access secret keys.?

**Comment by timothycarambat** [comment]
Yes, you can just set the env keys directly in the .env

```.env
LLM_PROVIDER='bedrock'
AWS_BEDROCK_LLM_ACCESS_KEY_ID=YOUR_KEY
AWS_BEDROCK_LLM_ACCESS_KEY=ACCESS_KEY_HERE
AWS_BEDROCK_LLM_REGION=us-west-2
AWS_BEDROCK_LLM_MODEL_PREFERENCE=meta.llama3-8b-instruct-v1:0
AWS_BEDROCK_LLM_MODEL_TOKEN_LIMIT=8191
```
